[profile.default]
src = "src"
out = "out"
libs = ["lib"]
[rpc_endpoints]
eth = "https://sepolia.infura.io/v3/YOUR_INFURA_KEY"
arb = "https://arb-sepolia.g.alchemy.com/v2/YOUR_ALCHEMY_KEY"


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
